export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";
export const FETCH_CURRENT_USER = "FETCH_USER_CURRENT";
export const SET_FIREBASE_USER = "SET_FIREBASE_USER";
export const FETCHED_USER_PROFILE = "FETCHED_USER_PROFILE";
export const FETCHED_USER_FAILED = "FETCHED_USER_FAILED";
